In [1]:
import numpy as np

In [2]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.zeros(4)

array([0., 0., 0., 0.])

In [7]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [9]:
#identity matrix|
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
np.random.rand(4)

array([0.91383397, 0.63422808, 0.01073702, 0.25307055])

In [11]:
np.random.randn(4)

array([-0.33977623, -0.08355056, -0.71600216, -1.2455732 ])

In [12]:
np.random.randn(5,5)

array([[ 0.08251031,  0.33895592, -0.03868719,  2.58007338, -0.28603336],
       [ 0.94090775, -0.37589129,  1.57852499, -1.56993462, -0.70701809],
       [-0.73868642, -0.25843284, -1.43897089, -0.61848767, -0.35464867],
       [-1.02201881,  1.73664952,  1.41256063, -0.07434333,  0.02017138],
       [ 0.07507988,  0.29071149, -2.56027832, -0.9510587 , -0.69723911]])

In [18]:
#give integer
arr=np.random.randint(0,100,6)
arr

array([ 5, 33, 79, 83,  4, 34])

In [17]:
arr.reshape(2,3)

array([[86, 93, 50],
       [ 0,  5, 55]])

In [20]:
arr.min()

np.int64(4)

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr[4]

np.int64(4)

In [25]:
arr[2:5]

array([2, 3, 4])

In [26]:
#reverse indexing
arr[-1]

np.int64(9)

In [28]:
arr[2:5]=99
arr

array([ 0,  1, 99, 99, 99,  5,  6,  7,  8,  9])

In [30]:
arr=np.array([[1,2],[3,4],[6,7]])
arr

array([[1, 2],
       [3, 4],
       [6, 7]])

In [32]:
arr[1]

array([3, 4])

In [33]:
arr[0,1]

np.int64(2)

In [35]:
arr2=np.arange(0,10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr2[arr2>2]


array([3, 4, 5, 6, 7, 8, 9])

In [39]:
arr2+arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
arr3=np.arange(3,13)
arr3


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
arr2*arr3

array([  0,   4,  10,  18,  28,  40,  54,  70,  88, 108])

In [45]:
#universal operation
np.sqrt(arr2)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])